export interface BlogPost {
  slug: string;
  title: string;
  description: string;
  date: string;
  readTime: number;
  category: string;
  coverEmoji: string;
  keywords: string[];
  content: string;
}

export const blogPosts: BlogPost[] = [
  {
    slug: "erdek-nerede-nasil-gidilir",
    title: "Erdek Nerede? Nasil Gidilir? — Ulasim Rehberi 2025",
    description: "Erdek nerede sorusunun cevabi, Istanbul, Ankara, Izmir'den Erdek'e nasil gidilir, otobus, feribot ve arac ile ulasim secenekleri.",
    date: "2025-06-01",
    readTime: 6,
    category: "Gezi Rehberi",
    coverEmoji: "🗺️",
    keywords: ["erdek nerede", "erdek nasil gidilir", "erdek ulasim", "erdek otobus", "erdek feribot", "balikesir erdek"],
    content: "<p>Erdek, Turkiye'nin kuzeybatisinda, <strong>Balikesir iline bagli</strong> bir ilce ve tatil beldesidir. Marmara Denizi'nin guney kiyisinda, Kapidag Yarimadasi'nin bati ucunda konumlanir.</p><h2>Erdek Nerede?</h2><p>Erdek ilcesi, Balikesir il merkezine yaklasik <strong>95 km</strong> uzaklikta, Marmara Denizi kiyisinda yer alir. Istanbul'a kus ucusu yaklasik 170 km mesafededir.</p><h2>Istanbul'dan Erdek'e Nasil Gidilir?</h2><h3>Otobus ile</h3><p>Istanbul Esenler veya Buyukcekekmece otobus terminallerinden Erdek'e direkt otobus seferleri mevcuttur. Yolculuk suresi yaklasik <strong>3,5-4 saat</strong>tir.</p><h3>Feribot ile</h3><p>Daha keyifli bir alternatif: Istanbul Yenikapi'dan Bandirma'ya feribot (yaklasik 2 saat), ardindan Bandirma'dan Erdek'e miniibus (40 dakika). IDO ve BUDO feribotlari bu hatti isletmektedir.</p><h3>Arac ile</h3><p>Istanbul'dan TEM Otoyolu - Bursa - Mustafakemalpasa - Bandirma - Erdek guzergahini izleyebilirsiniz. Toplam mesafe yaklasik <strong>230 km</strong>, yolculuk suresi 3-3,5 saattir.</p><h2>Ankara'dan Erdek'e Nasil Gidilir?</h2><p>Ankara'dan Erdek'e direkt otobus bulunabilir; aksi halde Bandirma aktarmali gidilir. Aracla yaklasik <strong>350 km</strong> ve 4,5 saattir.</p><h2>Erdek Icinde Ulasim</h2><p>Erdek merkezi yuruyuse oldukca elveriislidir. Cevre koylere ve Kapidag Yarimadasi'na dolmuslar islemektedir. Yazin kiralik bisiklet ve motosiklet secenekleri de mevcuttur.</p><p>Erdek'te konaklama aramak icin <a href='/konaklama'>ErdekOnline konaklama sayfasini</a> ziyaret edin!</p>",
  },
  {
    slug: "erdek-gezilecek-yerler",
    title: "Erdek'te Gezilecek Yerler — 2025 Tam Rehber",
    description: "Erdek'te mutlaka gorulmesi gereken yerler: Kapidag Yarimadasi, Marmara Adalari, tarihi mekanlar, plajlar ve dogal guzellikler.",
    date: "2025-06-05",
    readTime: 8,
    category: "Gezi Rehberi",
    coverEmoji: "🏝️",
    keywords: ["erdek gezilecek yerler", "erdek gorulecek yerler", "erdek tatil", "kapidag yarimadasi", "erdek ne yapilir"],
    content: "<p>Erdek, hem tarihi hem de dogal guzellikleriyle one cikan bir tatil beldesidir.</p><h2>1. Kapidag Yarimadasi</h2><p>Erdek'in en buyuk hazinesi olan <strong>Kapidag Yarimadasi</strong>, ormanlik tepeleri, kristal berrakligindaki koylari ve dogal yuruyus parkurlariyla doga tutkunlarinin gozdesidir.</p><h2>2. Erdek Sahil Seridi</h2><p>Erdek sahil seridi, yuruyus yapilabilecek genis bir promenad ve cevresindeki kafeler ile restoranlarla hareketli bir yasam sunar.</p><h2>3. Marmara Adalari</h2><p>Erdek iskelesi, Marmara Adalari'na duzenli feribot seferlerinin kalkis noktasidir. <strong>Marmara Adasi, Avsa ve Pasalimani</strong> gunubirlik veya konaklanarak ziyaret edilebilir.</p><h2>4. Ocaklar Koyu</h2><p>Turkuaz rengi koyu ve bozulmamis dogasiyla Ege tatil beldelerini aratmaz.</p><h2>5. Narli Golu</h2><p>Kapidag'da yer alan <strong>Narli Golu</strong>, tatli ve tuzlu suyun bulustuugu nadir bir lagunudur.</p><h2>6. Tekne Turlari</h2><p>Erdek iskelesinden kalkan <strong>mavi yolculuk tekneleri</strong>, gunubirlik koy turlari duzenler. <a href='/tekne'>Tekne turu seceneklerini gorun.</a></p>",
  },
  {
    slug: "erdek-plajlari",
    title: "Erdek Plajlari — En Iyi 7 Plaj ve Koy 2025",
    description: "Erdek'in en guzel plajlari ve koylari: Ocaklar, Turan, Yenikos, Kapidag koylari ve daha fazlasi.",
    date: "2025-06-10",
    readTime: 7,
    category: "Plaj & Deniz",
    coverEmoji: "🏖️",
    keywords: ["erdek plajlari", "erdek plaj", "erdek koylari", "erdek deniz", "ocaklar plaji", "kapidag koylari"],
    content: "<p>Erdek ve Kapidag Yarimadasi, Marmara Denizi'nin en temiz sularina ev sahipligi yapar.</p><h2>1. Erdek Merkez Plaji</h2><p>Sehire yurume mesafesinde, genis kum seridiyle aileler icin idealdir.</p><h2>2. Ocaklar Plaji</h2><p>Erdek'e 8 km mesafedeki <strong>Ocaklar Koyu</strong>, berrak turkuaz suyu ve sakin atmosferiyle en populer plajlardan biridir.</p><h2>3. Turan Plaji</h2><p>Kalabaliktan uzak olmak isteyenler icin mukemmeldir.</p><h2>4. Yenikos Plaji</h2><p>Golgeli agaclari ve sig kiyisiyla cocuklu aileler icin en guvenli seceneklerden biridir.</p><h2>5. Kapidag Koylari</h2><p>Yarimada boyunca tekneyle ulasilabilen onlarca gizli koy bulunur. <a href='/tekne'>Erdek tekne turlarina bakin.</a></p><h2>6. Narli Gol Kiyisi</h2><p>Hem tatli hem tuzlu suya sahip lagun kiyisi farkli bir deneyim sunar.</p><h2>7. Ballipinar Koyu</h2><p>Cam ormanlarina cevrili, sakin denizle bir cennet kosesidir. Kamp icin de idealdir.</p>",
  },
  {
    slug: "erdek-restoranlar-yemek",
    title: "Erdek'te Yemek — En Iyi Restoranlar ve Lezzetler 2025",
    description: "Erdek'te yemek yenecek en iyi restoranlar, balik lokantalar ve yoresel lezzetler.",
    date: "2025-06-15",
    readTime: 6,
    category: "Yemek & Lezzet",
    coverEmoji: "🍽️",
    keywords: ["erdek restoranlar", "erdek yemek", "erdek balik restoran", "erdek kahvalti", "erdek lezzetleri"],
    content: "<p>Marmara kiyisinda bir balikci kasabasi olan Erdek, taze deniz urunleri ile gastronomi tutkunlarini cezbeder.</p><h2>Yoresel Lezzetler</h2><p>Levrek, cipura, lufer ve kalkan Marmara'nin bol urunleridir. <strong>Midye dolma</strong>, <strong>Kapidag zeytinyaglilari</strong> ve Marmara bali de one cikar.</p><h2>Balik Restoranlari</h2><p>Erdek rihtimi boyunca siralanan balik restoranlari sabahın erken saatlerinde gelen taze baligi ayni gun servis eder. Gun batiminda denizi izleyerek balik yemek Erdek'in vazgecilmez deneyimlerindendir.</p><p>Online siparis icin <a href='/yemek'>ErdekOnline yemek platformunu</a> kullanabilirsiniz.</p>",
  },
  {
    slug: "erdek-tekne-turu-rehberi",
    title: "Erdek Tekne Turu Rehberi 2025 — Koylar ve Ipuclari",
    description: "Erdek tekne turlari hakkinda her sey: hangi koylar ziyaret edilir, gunubirlik ve cok gunluk tur secenekleri.",
    date: "2025-06-20",
    readTime: 7,
    category: "Tekne & Deniz",
    coverEmoji: "⛵",
    keywords: ["erdek tekne turu", "erdek tekne", "kapidag tekne turu", "erdek mavi yolculuk", "erdek koy turu"],
    content: "<p>Erdek, Kapidag Yarimadasi'nin cevreledigi kristal sulara tekne cikarmak icin Marmara'nin en ideal noktalarindan biridir.</p><h2>Ziyaret Edilen Koylar</h2><p><strong>Ballipinar Koyu</strong>, <strong>Narli Gol</strong>, <strong>Ocaklar Koyu</strong>, Yigitler ve Ilhan Koylari standart rota uzerindedir.</p><h2>Gunubirlik Tur</h2><p>Sabah 09:00'da kalkan, aksam 17:00'de donen gunubirlik koy turu en populer secenektir. Ogle yemegi ve snorkel ekipmani dahildir.</p><p>Rezervasyon icin <a href='/tekne'>ErdekOnline tekne turlari sayfasina</a> bakin.</p>",
  },
  {
    slug: "erdek-konaklama-rehberi",
    title: "Erdek'te Konaklama Rehberi 2025 — Oteller ve Pansiyonlar",
    description: "Erdek'te konaklama secenekleri: oteller, pansiyonlar, tatil evleri. Butcenize gore en iyi Erdek konaklama.",
    date: "2025-06-25",
    readTime: 6,
    category: "Konaklama",
    coverEmoji: "🏨",
    keywords: ["erdek konaklama", "erdek otel", "erdek pansiyon", "erdek tatil evi", "erdek apart"],
    content: "<p>Erdek, her butceye uygun genis bir konaklama yelpazesi sunar.</p><h2>Oteller</h2><p>Sahil seridindeki oteller deniz manzarasi ile one cikar. Temmuz-Agustos doneminde <strong>erken rezervasyon</strong> siddetle tavsiye edilir.</p><h2>Pansiyonlar</h2><p>Kapidag koylerindeki aile pansiyonlari otantik tatil arayanlar icin idealdir. Genellikle ev yapimi kahvalti dahildir.</p><h2>En Iyi Donem</h2><p><strong>Haziran ve Eylul</strong>, fiyatlarin uygun ve Erdek'in sakin oldugu donemdir.</p><p><a href='/konaklama'>ErdekOnline konaklama sayfasinda</a> tum secenekleri karsilastirin.</p>",
  },
  {
    slug: "erdek-hakkinda-her-sey",
    title: "Erdek Hakkinda Her Sey — Tarih, Kultur ve Yasam 2025",
    description: "Erdek ilcesinin tarihi, cografyasi, ekonomisi ve kulturel ozellikleri. Kapsamli Erdek rehberi.",
    date: "2025-07-01",
    readTime: 9,
    category: "Erdek Rehberi",
    coverEmoji: "🏘️",
    keywords: ["erdek hakkinda", "erdek tarihi", "erdek ilcesi", "erdek nufusu", "erdek ekonomisi"],
    content: "<p>Erdek, Marmara Denizi'nin guney kiyisinda, Kapidag Yarimadasi'nin bati ucunda yer alan tarihi bir Balikesir ilcesidir.</p><h2>Tarihi</h2><p>Erdek'in tarihi antik caglara uzanir. Bugunki Erdek'in bulundugu yerde antik cagda <strong>Artake</strong> adli bir yerlesim yeri vardi. Bolge Bizans, Osmanli ve Cumhuriyet donemlerini yasamistir.</p><h2>Ekonomi</h2><p>Temel ekonomik faaliyet alanlari: <strong>turizm</strong>, <strong>balikclik</strong>, <strong>zeytinyagi uretimi</strong> ve <strong>bagcilik</strong>.</p><h2>Kultur</h2><p>Erdek, Ege ve Marmara kulturunun harmanlandigi bir yasam tarzina sahiptir. Balikci kahvehaneleri ve sahil cafeler gunluk yasamin merkezindedir.</p>",
  },
  {
    slug: "erdeke-ne-zaman-gidilir",
    title: "Erdek'e Ne Zaman Gidilir? — Sezon Rehberi 2025",
    description: "Erdek'e gitmek icin en iyi donem hangisi? Hava durumu, deniz sicakliklari ve sezon bilgileriyle tatil planlamasi.",
    date: "2025-07-05",
    readTime: 5,
    category: "Gezi Rehberi",
    coverEmoji: "📅",
    keywords: ["erdek ne zaman gidilir", "erdek hava durumu", "erdek sezon", "erdek yaz tatili", "erdek deniz sicakligi"],
    content: "<p>Erdek'e ne zaman gideceginize karar vermek tatil deneyiminizi dogrudan etkiler.</p><h2>Ilkbahar (Nisan-Mayis)</h2><p>Ormanlar yemyesil, fiyatlar dusuk. Deniz henuz soguk ama doga yuruyusu ve fotograf icin mukemmel.</p><h2>Yaz (Haziran-Agustos)</h2><p>En kalabalik donem, deniz 22-27 derece. <strong>Erken rezervasyon sart.</strong> Haziran basi ve Eylul basi en ideal zamanlardir.</p><h2>Erken Sonbahar (Eylul-Ekim)</h2><p>En cok onerilen donem: deniz hala sicak, kalabalik azalmis, fiyatlar dusmus.</p><h2>Kis (Kasim-Mart)</h2><p>Sakin ve issiz. Fiyatlar en dusuk seviyede, uzlete cekilmek icin ideal.</p><ul><li><strong>Deniz tatili:</strong> Haziran ortasi - Eylul basi</li><li><strong>Ekonomik tatil:</strong> Haziran ilk haftasi veya Eylul-Ekim</li><li><strong>Doga yuruyusu:</strong> Nisan-Mayis veya Ekim</li></ul><p><a href='/'>ErdekOnline</a> ile konaklama, yemek ve tekne turunu tek platformdan planlayabilirsiniz.</p>",
  },
  {
    slug: "kapıdag-yarimadasi-rehberi",
    title: "Kapıdağ Yarımadası Rehberi — Koylar, Yürüyüş ve Doğa 2025",
    description: "Kapıdağ Yarımadası'nın tüm koyları, yürüyüş parkurları ve doğal güzellikleri. Erdek'ten nasıl gidilir?",
    date: "2025-07-08",
    readTime: 8,
    category: "Doğa & Yürüyüş",
    coverEmoji: "🌲",
    keywords: ["kapıdağ yarımadası", "kapıdağ koyları", "kapıdağ yürüyüş", "erdek kapıdağ", "kapıdağ gizli koylar"],
    content: "<p><strong>Kapıdağ Yarımadası</strong>, Erdek'e bağlı Marmara Denizi'ne uzanan yeşil ve mavi bir cennet şerididir. Yaklaşık 50 km uzunluğundaki yarımada onlarca saklı koyu ve el değmemiş ormanlarıyla yılın her mevsimi ziyarete değer.</p><h2>Başlıca Koylar</h2><ul><li><strong>Ocaklar:</strong> En popüler koy, berrak deniz ve çam ormanı</li><li><strong>Narlı:</strong> Lagün gölü ve kamp alanları</li><li><strong>Baldım:</strong> Sakin, aileler için ideal</li><li><strong>Domurcalı:</strong> Gizli cennet</li><li><strong>Hamzaköy:</strong> Küçük marina ve balıkçı restoranları</li></ul><h2>Yürüyüş Parkurları</h2><p>Yarımada boyunca ormanlık yürüyüş parkurları Nisan-Haziran ve Eylül-Kasım dönemlerinde harikadır. Kapıdağ tepesinden Marmara manzarası nefes kesicidir.</p>",
  },
  {
    slug: "avsa-adası-erdekten-nasil-gidilir",
    title: "Avşa Adası'na Erdek'ten Nasıl Gidilir? — Feribot Rehberi 2025",
    description: "Erdek'ten Avşa Adası'na feribot saatleri, bilet fiyatları ve günübirlik gezi planı.",
    date: "2025-07-10",
    readTime: 6,
    category: "Günübirlik Geziler",
    coverEmoji: "🚢",
    keywords: ["avşa adası erdek", "erdekten avşa feribot", "avşa adası nasıl gidilir", "avşa feribot saatleri"],
    content: "<p>Erdek, Marmara adalarına en kolay ulaşılan kalkış noktasıdır. <strong>Avşa Adası</strong>, Erdek iskelesine yaklaşık 1 saat 15 dakika uzaklıktadır.</p><h2>Feribot Bilgileri</h2><p>Yaz sezonunda Erdek'ten Avşa'ya günde 3-5 sefer düzenlenmektedir. Bilet 150-200 TL (2025).</p><h2>Avşa'da Gezilecek Yerler</h2><ul><li><strong>Avşa Merkez Plajı:</strong> Uzun kumsal</li><li><strong>Türkeli Koyu:</strong> Turkuaz su</li><li><strong>Bağlar Tepesi:</strong> Panoramik manzara</li></ul><h2>Günübirlik Plan</h2><p>Sabah 08:00 feribotu, öğle yemeği adada, saat 16:00 dönüş. Mükemmel bir günübirlik!</p>",
  },
  {
    slug: "marmara-adası-gezi-rehberi",
    title: "Marmara Adası Gezi Rehberi — Erdek'ten Günübirlik 2025",
    description: "Marmara Adası'na Erdek'ten nasıl gidilir, mermerleri, plajları ve tarihi hakkında kapsamlı rehber.",
    date: "2025-07-12",
    readTime: 7,
    category: "Günübirlik Geziler",
    coverEmoji: "🏔️",
    keywords: ["marmara adası", "erdekten marmara adası", "marmara adası gezisi", "marmara adası mermer", "marmara adası feribot"],
    content: "<p><strong>Marmara Adası</strong>, adını dünyaca ünlü beyaz mermerinden alan Marmara Denizi'nin en büyük adasıdır.</p><h2>Erdek'ten Ulaşım</h2><p>Erdek iskelesinden Marmara Adası'na düzenli feribot seferleri mevcuttur. Yolculuk süresi yaklaşık 2 saattir.</p><h2>Adada Gezilecek Yerler</h2><ul><li><strong>Saraylar Koyu:</strong> Adanın en güzel plajı</li><li><strong>Mermer Ocakları:</strong> Tarihi çıkarma alanları</li><li><strong>Çınarlı Köy:</strong> Otantik taş evler</li></ul><h2>Ada Mutfağı</h2><p>Taze balık, midye ve yerel zeytinyağı ürünleri mutlaka denenmelidir.</p>",
  },
  {
    slug: "erdek-kamp-alanlari",
    title: "Erdek Kamp Alanları — En İyi Kamp Yerleri 2025",
    description: "Erdek ve Kapıdağ'daki kamp alanları, ücretler, olanaklar ve kamp yaparken dikkat edilmesi gerekenler.",
    date: "2025-07-15",
    readTime: 6,
    category: "Doğa & Yürüyüş",
    coverEmoji: "⛺",
    keywords: ["erdek kamp", "kapıdağ kamp alanı", "erdek kamp yeri", "narlı göl kamp", "erdek çadır kamp"],
    content: "<p>Erdek ve Kapıdağ Yarımadası, Türkiye'nin en güzel kamp destinasyonlarından biridir. Çam ormanları, deniz manzarası ve temiz hava bir arada sunulur.</p><h2>Narlı Gölü Kamp Alanı</h2><p><strong>Narlı Gölü</strong> çevresindeki kamp alanları hem tatlı su lagününe hem de denize yakınlığıyla benzersizdir. Tuvalet, duş ve elektrik mevcuttur.</p><h2>Ocaklar Kamp Alanları</h2><p>Ocaklar Koyu'nun çam gölgesindeki alanlar denize yürüme mesafesindedir. Yaz sezonunda önceden rezervasyon önerilir.</p><h2>Kamp İpuçları</h2><ul><li>Temmuz-Ağustos'ta kesinlikle rezervasyon yapın</li><li>Sivrisinek ilacı ve güneş kremi şart</li><li>En yakın market Erdek merkezde</li></ul>",
  },
  {
    slug: "erdek-balik-restoranlari",
    title: "Erdek'in En İyi Balık Restoranları 2025",
    description: "Erdek'te balık yenecek en iyi restoranlar, taze deniz ürünleri ve fiyat bilgileri.",
    date: "2025-07-18",
    readTime: 5,
    category: "Yemek & Lezzet",
    coverEmoji: "🍽️",
    keywords: ["erdek balık restoran", "erdek balıkçı", "erdek deniz ürünleri", "erdek sahil restoran"],
    content: "<p>Erdek, Marmara'nın taze nimetlerini sofraya taşıyan restoranlarıyla meşhurdur. Sahil şeridindeki balıkçı restoranlar sabah avlanan balıkları aynı gün servis eder.</p><h2>Ne Sipariş Etmeli?</h2><ul><li><strong>Lüfer:</strong> Ekim-Kasım en ideal dönem</li><li><strong>Çipura ve Levrek:</strong> Yaz boyunca taze</li><li><strong>Midye tava:</strong> Vazgeçilmez meze</li><li><strong>Ahtapot ızgara:</strong> Özel lezzet</li></ul><h2>Fiyat Aralığı</h2><p>Kişi başı ortalama 250-500 TL (2025, içecek dahil). Temmuz-Ağustos'ta rezervasyon şart.</p>",
  },
  {
    slug: "erdek-ailece-tatil-rehberi",
    title: "Erdek'te Ailece Tatil — Çocuklu Aileler İçin Rehber 2025",
    description: "Erdek'te çocuklu aileler için en iyi aktiviteler, güvenli plajlar ve konaklama önerileri.",
    date: "2025-07-20",
    readTime: 7,
    category: "Gezi Rehberi",
    coverEmoji: "👨‍👩‍👧‍👦",
    keywords: ["erdek aile tatili", "erdek çocuklu tatil", "erdek çocuk plajı", "erdek aile oteli"],
    content: "<p>Erdek, sakin denizi ve çocuk dostu atmosferiyle aileler için mükemmel bir tatil rotasıdır.</p><h2>Aileler İçin En İyi Plajlar</h2><ul><li><strong>Turan Plajı:</strong> Sığ giriş, güvenli</li><li><strong>Erdek Merkez Plajı:</strong> Denetimli alan</li><li><strong>Baldım Koyu:</strong> Sakin, kalabalık değil</li></ul><h2>Çocuklarla Aktiviteler</h2><ul><li>Günlük tekne turu</li><li>Bisikletle sahil turu</li><li>Narlı Gölü'nde doğa yürüyüşü</li></ul><h2>Konaklama</h2><p>Apart oteller mutfak imkânı sunduğu için çocuklu aileler için idealdir.</p>",
  },
  {
    slug: "erdek-fotografcilik-noktalari",
    title: "Erdek'te Fotoğrafçılık — En Güzel Manzara Noktaları 2025",
    description: "Erdek ve Kapıdağ'da fotoğraf çekmek için en iyi noktalar, gün batımı ve Instagram'lık lokasyonlar.",
    date: "2025-07-22",
    readTime: 5,
    category: "Gezi Rehberi",
    coverEmoji: "📸",
    keywords: ["erdek fotoğraf", "erdek manzara", "erdek gün batımı", "kapıdağ fotoğraf", "erdek instagram"],
    content: "<p>Erdek, fotoğraf tutkunları için Marmara'nın en zengin destinasyonlarından biridir.</p><h2>En İyi Fotoğraf Noktaları</h2><ul><li><strong>Erdek İskelesi:</strong> Gün batımında tekneler muhteşem</li><li><strong>Kapıdağ Tepesi:</strong> 360 derece panoramik manzara</li><li><strong>Ocaklar Koyu:</strong> Turkuaz su ve çam ağaçları</li><li><strong>Narlı Gölü:</strong> Lagün ve denizin buluştuğu çerçeve</li></ul><h2>En İyi Zaman</h2><p>Gün batımından 1 saat önce altın ışık Erdek'te büyülüdür. Eylül-Ekim fotoğraf için en ideal dönemdir.</p>",
  },
  {
    slug: "erdek-dalıs-su-sporlari",
    title: "Erdek'te Dalış ve Su Sporları — Aktivite Rehberi 2025",
    description: "Erdek'te dalış noktaları, kano, jet ski ve diğer su sporları hakkında kapsamlı rehber.",
    date: "2025-07-25",
    readTime: 6,
    category: "Aktiviteler",
    coverEmoji: "🤿",
    keywords: ["erdek dalış", "erdek su sporları", "erdek kano", "erdek jet ski", "kapıdağ dalış"],
    content: "<p>Erdek ve Kapıdağ koylarının berrak suları su sporları için ideal koşullar sunar.</p><h2>Dalış</h2><p>Kapıdağ koylarında 5-15 metre derinlikte renkli deniz tabanı, ahtapot ve levrek görülebilir.</p><h2>Kano ve Kürek</h2><p>Sakin koylar kano için mükemmeldir. Kano kiralama hizmetleri Ocaklar'da bulunur.</p><h2>Jet Ski</h2><p>Erdek sahilinde ve Ocaklar'da jet ski kiralama noktaları faaliyet göstermektedir.</p><h2>Snorkeling</h2><p>Maske ve şnorkel ile Ocaklar ve Baldım koylarında zengin deniz altı hayatını keşfedebilirsiniz.</p>",
  },
  {
    slug: "erdek-ulasim-dolmus-taksi",
    title: "Erdek'te Ulaşım Rehberi — Dolmuş, Taksi ve Bisiklet 2025",
    description: "Erdek içi ulaşım: dolmuş hatları, taksi ücretleri, kiralık araç ve bisiklet seçenekleri.",
    date: "2025-07-28",
    readTime: 5,
    category: "Pratik Bilgiler",
    coverEmoji: "🚌",
    keywords: ["erdek dolmuş", "erdek taksi", "erdek içi ulaşım", "kapıdağ dolmuş", "erdek kiralık araç"],
    content: "<p>Erdek merkezi yürüyüşe elverişli olsa da çevre koylar için ulaşım planlaması önemlidir.</p><h2>Dolmuş</h2><p>Erdek merkezden Ocaklar, Narlı ve diğer Kapıdağ koylarına düzenli dolmuş seferleri işlemektedir.</p><h2>Taksi</h2><p>Binmeden önce fiyatı sorun. Erdek-Ocaklar arası yaklaşık 80-120 TL (2025).</p><h2>Kiralık Bisiklet</h2><p>Sahil boyunca bisiklet kiralama noktaları vardır. Sahil şeridini bisikletle keşfetmek hem ekonomik hem keyiflidir.</p>",
  },
  {
    slug: "erdek-alisveris-market-pazar",
    title: "Erdek'te Alışveriş — Marketler, Pazar ve Hediyelik Eşya 2025",
    description: "Erdek'te market, çarşı ve alışveriş yerleri. Yerel ürünler, hediyelik eşya ve pazar günleri rehberi.",
    date: "2025-08-01",
    readTime: 4,
    category: "Pratik Bilgiler",
    coverEmoji: "🛒",
    keywords: ["erdek market", "erdek alışveriş", "erdek pazar", "erdek hediyelik", "erdek zeytinyağı"],
    content: "<p>Erdek'te alışveriş etmek hem kolay hem keyiflidir.</p><h2>Zincir Marketler</h2><p>Erdek merkezde Migros, BİM ve A101 gibi zincir marketler mevcuttur. Tatil sezonunda uzun saatler açık kalırlar.</p><h2>Yerel Pazar</h2><p>Haftalık kurulan pazarda yerel üreticilerin taze ürünleri, peynirler ve zeytinyağı bulunur.</p><h2>En İyi Hediyelikler</h2><ul><li><strong>Kapıdağ zeytinyağı:</strong> Bölgenin birinci sınıf ürünü</li><li><strong>Marmara mermeri:</strong> Küçük dekoratif objeler</li><li><strong>Yerel bal:</strong> Kapıdağ çam balı meşhurdur</li></ul>",
  },
  {
    slug: "erdek-gece-hayati-kafeler",
    title: "Erdek'te Gece Hayatı — Barlar, Kafeler ve Akşam Aktiviteleri 2025",
    description: "Erdek'te akşamları ne yapılır? Sahil barları, canlı müzik mekanları ve gece aktiviteleri.",
    date: "2025-08-05",
    readTime: 5,
    category: "Aktiviteler",
    coverEmoji: "🌙",
    keywords: ["erdek gece hayatı", "erdek bar", "erdek kafe", "erdek akşam", "erdek canlı müzik"],
    content: "<p>Erdek'in gece hayatı sahil şeridindeki kafeler ve barlarla keyifli akşamlar sunar.</p><h2>Sahil Kafeleri</h2><p>Erdek sahil promenadındaki kafeler gün batımı manzarasıyla akşam saatlerinde dolup taşar.</p><h2>Balık Restoranları</h2><p>Akşam yemeği için en iyi seçenek sahildeki balık restoranlarıdır. Rakı-balık geleneği Erdek'te yaşatılmaktadır.</p><h2>Yaz Etkinlikleri</h2><p>Temmuz-Ağustos döneminde Erdek'te çeşitli açık hava etkinlikleri ve konserler düzenlenmektedir.</p>",
  },
  {
    slug: "erdek-zeytinyagi-uretimi",
    title: "Kapıdağ Zeytinyağı — Yerel Üretim ve Satın Alma Rehberi",
    description: "Kapıdağ Yarımadası'nın ünlü zeytinyağı üretimi, çiftlik ziyaretleri ve kaliteli zeytinyağı nereden alınır.",
    date: "2025-08-08",
    readTime: 6,
    category: "Yemek & Lezzet",
    coverEmoji: "🫒",
    keywords: ["erdek zeytinyağı", "kapıdağ zeytinyağı", "erdek zeytin", "kapıdağ zeytin çiftliği", "erdek yerel ürün"],
    content: "<p>Kapıdağ Yarımadası, Türkiye'nin en kaliteli zeytinyağlarından birinin üretildiği bölgedir.</p><h2>Kapıdağ Zeytinyağının Özellikleri</h2><p>Düşük asit oranı ve meyvemsi aromasıyla öne çıkan Kapıdağ zeytinyağı, soğuk sıkım yöntemiyle üretilir.</p><h2>Nereden Alınır?</h2><ul><li>Erdek merkez pazarında yerel üreticilerden</li><li>Kapıdağ koylarındaki çiftlik satış noktalarından</li></ul><h2>Zeytin Hasadı</h2><p>Ekim-Kasım aylarında gerçekleşen <strong>zeytin hasadı</strong> döneminde Kapıdağ'ı ziyaret edin; çiftliklerde hasat deneyimine katılmak mümkündür.</p>",
  },
  {
    slug: "erdek-balıkçılık-kultur",
    title: "Erdek'te Balıkçılık Kültürü — Sabah Pazarı ve Tekne Turu",
    description: "Erdek balıkçılık geleneği, sabah balık pazarı, balıkçı tekneleriyle tur ve taze balık alma rehberi.",
    date: "2025-08-10",
    readTime: 5,
    category: "Erdek Rehberi",
    coverEmoji: "🎣",
    keywords: ["erdek balıkçılık", "erdek balık pazarı", "erdek balıkçı teknesi", "erdek balık turu"],
    content: "<p>Balıkçılık, Erdek'in kimliğinin ayrılmaz bir parçasıdır. Sahildeki balıkçı kahvehaneleri ve sabah erken dönen tekneler bu geleneğin canlı tanıklarıdır.</p><h2>Sabah Balık Pazarı</h2><p>Erdek iskelesi yakınlarında sabah erken saatlerde kurulan balık tezgahlarında günün taze avını bulabilirsiniz. En taze ürünler <strong>07:00-09:00</strong> arasında satılır.</p><h2>Balık Tutma Turu</h2><p>Bazı balıkçılar turistlere sabah turları düzenlemektedir. Gün doğumunda tekneye binin, Marmara açıklarında balık tutun.</p><h2>Hangi Balıklar Tutulur?</h2><ul><li><strong>Çipura ve levrek:</strong> Yaz aylarında bol</li><li><strong>Lüfer:</strong> Sonbahar başı en lezzetli dönem</li><li><strong>Hamsi:</strong> Kış mevsiminin vazgeçilmezi</li></ul>",
  },
  {
    slug: "erdek-narli-golu-rehber",
    title: "Narlı Gölü Erdek — Kapıdağ'ın Saklı Lagünü Rehberi",
    description: "Kapıdağ Yarımadası'ndaki Narlı Gölü hakkında her şey: ulaşım, kamp, doğa yürüyüşü ve lagün özellikleri.",
    date: "2025-08-12",
    readTime: 6,
    category: "Doğa & Yürüyüş",
    coverEmoji: "🏞️",
    keywords: ["narlı gölü", "kapıdağ narlı göl", "erdek narlı göl", "kapıdağ lagün", "narlı gölü kamp"],
    content: "<p><strong>Narlı Gölü</strong>, Kapıdağ Yarımadası'nda denizle tatlı su gölünün buluştuğu Türkiye'nin nadir lagünlerinden biridir.</p><h2>Narlı Gölü Nerede?</h2><p>Erdek'e yaklaşık 20 km uzaklıkta, Kapıdağ Yarımadası'nın orta kesiminde yer alır. Erdek'ten dolmuşla 30-40 dakikada ulaşılabilir.</p><h2>Ne Yapılır?</h2><ul><li>Lagünde yüzme ve snorkeling</li><li>Çevresindeki ormanda yürüyüş</li><li>Kuş gözlemi (pelikan, balıkçıl)</li><li>Kamp yapma</li></ul><h2>En İyi Zaman</h2><p>İlkbahar ve sonbahar yürüyüş için; yaz ortası yüzme için idealdir.</p>",
  },
  {
    slug: "erdek-ocaklar-koyu-rehberi",
    title: "Ocaklar Koyu Erdek — Kapsamlı Koy Rehberi 2025",
    description: "Ocaklar Koyu'na ulaşım, plaj özellikleri, kamp alanları, restoranlar ve pratik bilgiler.",
    date: "2025-08-15",
    readTime: 6,
    category: "Plajlar",
    coverEmoji: "🏝️",
    keywords: ["ocaklar koyu", "ocaklar erdek", "ocaklar plajı", "ocaklar kamp", "kapıdağ ocaklar"],
    content: "<p><strong>Ocaklar Koyu</strong>, Erdek'e 12 km uzaklıkta Kapıdağ Yarımadası'nın en popüler koylarından biridir. Yemyeşil çam ormanları arasında saklı kristal suyu ile Ege koylarını aratmaz.</p><h2>Ulaşım</h2><p>Erdek merkezden Ocaklar'a dolmuş seferleri işlemektedir. Tekneyle gitmek daha keyiflidir.</p><h2>Plaj Özellikleri</h2><ul><li>Derin mavi-yeşil su</li><li>İnce çakıl ve kum karışımı zemin</li><li>Çam gölgesi bol</li><li>Şezlong ve şemsiye kiralama mevcut</li></ul><h2>Yeme-İçme</h2><p>Koy çevresinde birkaç balık restoranı ve kafe bulunmaktadır.</p>",
  },
  {
    slug: "erdek-sonbahar-tatili",
    title: "Eylül-Ekim'de Erdek Tatili — Sonbahar Rehberi 2025",
    description: "Sonbaharda Erdek'te tatil yapmak neden mantıklı? Deniz sıcaklığı, kalabalık durumu ve aktiviteler.",
    date: "2025-09-01",
    readTime: 6,
    category: "Gezi Rehberi",
    coverEmoji: "🍂",
    keywords: ["eylül erdek tatili", "ekim erdek", "erdek sonbahar", "erdek düşük sezon", "erdek ucuz tatil"],
    content: "<p>Pek çok tatilci Erdek'i yaz aylarıyla özdeşleştirse de <strong>Eylül ve Ekim</strong>, Erdek'i keşfetmek için belki de en iyi dönemdir.</p><h2>Neden Sonbahar?</h2><ul><li>Deniz suyu hâlâ 21-23 derece</li><li>Yaz kalabalığı yok, plajlar boş</li><li>Otel fiyatları yüzde 30-50 düşüyor</li><li>Zeytin hasadı dönemi — yerel deneyim</li></ul><h2>Sonbaharda Yapılacaklar</h2><ul><li>Kapıdağ ormanlarında yürüyüş</li><li>Narlı Gölü'nde kuş gözlemi</li><li>Zeytin hasadına katılım</li><li>Sahil kafelerinde sakin çay keyfi</li></ul>",
  },
  {
    slug: "erdek-kis-tatili-rehberi",
    title: "Kışın Erdek'te Tatil Yapmak — Kış Rehberi 2025",
    description: "Kış aylarında Erdek'e gitmek mantıklı mı? Ne bulursunuz, ne bulamazsınız ve kış tatilinin avantajları.",
    date: "2025-09-05",
    readTime: 5,
    category: "Gezi Rehberi",
    coverEmoji: "❄️",
    keywords: ["erdek kış tatili", "erdek kışın", "erdek kış", "kışın erdek nasıl", "erdek yılbaşı"],
    content: "<p>Kışın Erdek bambaşka bir yüz sunar: sakin sokaklar, ıssız plajlar ve derin bir huzur.</p><h2>Kışın Erdek'te Ne Bulursunuz?</h2><ul><li>Neredeyse boş sahiller ve koylar</li><li>Çok düşük fiyatlar</li><li>Açık balık restoranları (sayısı azalır)</li><li>Kapıdağ ormanları ıssız ve huzurlu</li></ul><h2>Kışın Kapalı Olanlar</h2><ul><li>Çoğu otel kapanır (açıkları önceden araştırın)</li><li>Dolmuş seferleri azalır</li><li>Ada feribot seferleri seyrelmesi</li></ul><h2>Tavsiye</h2><p>Yılbaşı döneminde Erdek'te sakin ve hesaplı bir tatil planlanabilir.</p>",
  },
  {
    slug: "erdek-ilkbahar-tatili",
    title: "İlkbaharda Erdek — Nisan ve Mayıs Rehberi 2025",
    description: "Nisan ve Mayıs'ta Erdek'e gitmek: yeşil Kapıdağ, çiçekli koylar, uygun fiyatlar ve hafta sonu kaçaması.",
    date: "2025-09-08",
    readTime: 5,
    category: "Gezi Rehberi",
    coverEmoji: "🌸",
    keywords: ["erdek nisan tatili", "erdek mayıs", "erdek ilkbahar", "erdek hafta sonu", "kapıdağ ilkbahar"],
    content: "<p>İlkbaharda Erdek, yaz kalabalığından uzak, yemyeşil ormanları ve çiçek açmış koylarıyla büyüleyici bir manzara sunar.</p><h2>İlkbaharda Erdek'in Güzellikleri</h2><ul><li>Kapıdağ ormanları en yeşil halinde</li><li>Yabani çiçekler koyları süsler</li><li>Kuş göçü dönemi</li></ul><h2>İlkbaharda Fiyatlar</h2><p>Nisan-Mayıs, fiyatların en düşük olduğu dönemdir. Yüzde 40-60 indirimli konaklama mümkündür.</p><h2>Hafta Sonu Kaçaması</h2><p>İstanbul'dan Erdek'e 3-4 saatte ulaşılabildiğinden hafta sonu kaçaması için mükemmel bir seçenektir.</p>",
  },
  {
    slug: "erdek-romantik-tatil-ciftler",
    title: "Erdek'te Romantik Tatil — Çiftler İçin Rehber 2025",
    description: "Erdek'te çiftler için en romantik aktiviteler, gün batımı noktaları ve özel tatil önerileri.",
    date: "2025-09-10",
    readTime: 5,
    category: "Gezi Rehberi",
    coverEmoji: "💑",
    keywords: ["erdek romantik tatil", "erdek çiftler", "erdek balayı", "erdek gün batımı", "erdek özel tatil"],
    content: "<p>Erdek, gürültüden uzak huzurlu atmosferiyle çiftler için mükemmel bir tatil destinasyonudur.</p><h2>Romantik Aktiviteler</h2><ul><li><strong>Gün batımında tekne turu:</strong> Kapıdağ koylarında akşam ışığında tekne keyfi</li><li><strong>İskele'de yürüyüş:</strong> El ele sahil yürüyüşü</li><li><strong>Özel balık yemeği:</strong> Mum ışığında akşam yemeği</li><li><strong>Narlı Gölü'nde şafak:</strong> Lagünde gün doğumu seyretmek</li></ul><h2>En Romantik Dönem</h2><p>Eylül başı; deniz sıcak, kalabalık azalmış, hava mükemmel. Çiftler için ideal.</p>",
  },
  {
    slug: "erdek-kahvalti-yerleri",
    title: "Erdek'te Kahvaltı Yerleri — En İyi Sabah Kafeleri 2025",
    description: "Erdek'te kahvaltı yapılacak en iyi mekanlar, serpme kahvaltı, sahil kafeleri ve yerel lezzetler.",
    date: "2025-09-12",
    readTime: 4,
    category: "Yemek & Lezzet",
    coverEmoji: "☕",
    keywords: ["erdek kahvaltı", "erdek kahvaltı yerleri", "erdek sabah kahvaltısı", "erdek kafe", "erdek serpme kahvaltı"],
    content: "<p>Erdek'te sabah kahvaltısı tatilin en keyifli ritüellerinden biridir. Sahil kafelerinde deniz manzarasıyla yapılan serpme kahvaltılar akıllardan çıkmaz.</p><h2>Erdek Kahvaltısında Ne Bulunur?</h2><ul><li>Kapıdağ zeytinyağı ve yerel zeytinler</li><li>Taze peynir çeşitleri</li><li>Ev yapımı reçeller</li><li>Taze balık veya sucuk omlet</li></ul><h2>Kahvaltı İçin En İyi Zaman</h2><p>Yazın erken saatlerde (07:00-09:00) kalkmak, hem serin havayı hem de en taze ürünleri yakalamak demektir.</p>",
  },
  {
    slug: "erdek-hediyelik-el-sanatlari",
    title: "Erdek Yerel El Sanatları ve Hediyelik Ürünler Rehberi",
    description: "Erdek'ten eve götürülecek en güzel hediyelikler: zeytinyağı sabunu, yerel bal, mermer objeler.",
    date: "2025-09-15",
    readTime: 4,
    category: "Pratik Bilgiler",
    coverEmoji: "🎁",
    keywords: ["erdek hediyelik", "erdek zeytinyağı sabunu", "kapıdağ hediyelik eşya", "erdek el sanatları"],
    content: "<p>Erdek'ten eve bir hatıra götürmek istiyorsanız doğru seçimler önemlidir.</p><h2>En İyi Hediyelikler</h2><ul><li><strong>Sızma zeytinyağı:</strong> Kapıdağ'ın birinci sınıf ürünü</li><li><strong>Zeytinyağı sabunu:</strong> El yapımı, doğal</li><li><strong>Marmara mermeri heykelcikler:</strong> Adadan getirilen özgün objeler</li><li><strong>Yerel bal:</strong> Kapıdağ çam balı meşhurdur</li><li><strong>Tuzlu balık ürünleri:</strong> Çiroz ve tuzlu levrek</li></ul><h2>Nereden Alınır?</h2><p>Erdek merkez pazarı ve sahil yakınındaki küçük dükkanlar bu ürünler için en iyi noktalardır.</p>",
  },
  {
    slug: "erdek-bayram-tatili-planlamasi",
    title: "Erdek'te Bayram Tatili — Planlama ve Rezervasyon Rehberi",
    description: "Bayram tatilinde Erdek'e gitmek için en iyi planlama rehberi: erken rezervasyon ve aktivite önerileri.",
    date: "2025-09-18",
    readTime: 5,
    category: "Gezi Rehberi",
    coverEmoji: "🎉",
    keywords: ["erdek bayram tatili", "erdek kurban bayramı", "erdek ramazan bayramı", "erdek tatil planı"],
    content: "<p>Bayram tatilleri Erdek için en yoğun dönemlerden biridir. Doğru planlama ile harika bir bayram tatili geçirebilirsiniz.</p><h2>Erken Rezervasyon Şart</h2><p>Bayram dönemlerinde Erdek'teki otel ve pansiyonlar <strong>2-3 ay önceden</strong> dolmaya başlar.</p><h2>Ulaşım Planlaması</h2><p>Bayram tatillerinde karayolu yoğunluğu artar. Feribot alternatifi daha rahat olabilir.</p><h2>Aktivite Önerileri</h2><ul><li>Sabah erken plaja giderek kalabalıktan kaçın</li><li>Tekne turu rezervasyonunu önceden yapın</li><li>Kapıdağ koyları merkeze göre daha sakin kalır</li></ul>",
  },
  {
    slug: "erdek-doga-yuruyus-parkurlari",
    title: "Erdek Doğa Yürüyüş Parkurları — Kapıdağ Trekking Rehberi",
    description: "Kapıdağ Yarımadası'ndaki yürüyüş parkurları, zorluk seviyeleri, manzara noktaları ve hazırlık ipuçları.",
    date: "2025-09-20",
    readTime: 7,
    category: "Doğa & Yürüyüş",
    coverEmoji: "🥾",
    keywords: ["erdek yürüyüş", "kapıdağ trekking", "kapıdağ doğa yürüyüşü", "erdek parkur", "kapıdağ hiking"],
    content: "<p>Kapıdağ Yarımadası, Türkiye'nin en güzel ve az keşfedilmiş yürüyüş destinasyonlarından biridir.</p><h2>Başlıca Parkurlar</h2><ul><li><strong>Erdek-Narlı Gölü Parkuru:</strong> Yaklaşık 8 km, orta zorluk</li><li><strong>Kapıdağ Tepesi Yürüyüşü:</strong> 5 km, zirveden 360 derece manzara</li><li><strong>Koy Koy Yürüyüş:</strong> Ocaklar'dan Baldım'a sahil boyunca</li></ul><h2>En İyi Sezon</h2><p>Nisan-Mayıs ve Eylül-Ekim en ideal dönemlerdir. Yaz ortasında sıcak ve yorucu olabilir.</p><h2>Hazırlık</h2><ul><li>Bol su ve atıştırmalık alın</li><li>Güneş kremi ve şapka şart</li><li>Sağlam yürüyüş ayakkabısı gerekli</li></ul>",
  },
  {
    slug: "erdek-istanbul-haftasonu-kacamasi",
    title: "İstanbul'dan Erdek'e Hafta Sonu Kaçaması — Tam Rehber",
    description: "İstanbul'dan Erdek'e hafta sonu kaçaması planı: feribot, otobüs, konaklama ve aktivite önerileri.",
    date: "2025-09-25",
    readTime: 6,
    category: "Gezi Rehberi",
    coverEmoji: "🏃",
    keywords: ["istanbul erdek hafta sonu", "istanbul erdek kaçış", "erdek feribot istanbul", "istanbul yakın tatil"],
    content: "<p>İstanbul'un kalabalığından bunaldıysanız Erdek mükemmel bir hafta sonu kaçaması sunar. Sadece 3-4 saatlik yolculukla Marmara kıyısına ulaşırsınız.</p><h2>Nasıl Gidilir?</h2><p><strong>En keyifli yol:</strong> Yenikapı-Bandırma feribotu (2 saat) + Bandırma'dan minibüs (45 dk) = toplam yaklaşık 3,5 saat.</p><h2>2 Gece 3 Günlük Plan</h2><ul><li><strong>Cuma akşamı:</strong> İstanbul'dan hareket</li><li><strong>Cumartesi:</strong> Tekne turu, plaj, sahil yürüyüşü</li><li><strong>Pazar:</strong> Kapıdağ yürüyüşü veya ada gezisi, öğleden sonra dönüş</li></ul>",
  },
  {
    slug: "erdek-tekne-kiralama-rehberi",
    title: "Erdek'te Tekne Kiralama — Fiyatlar ve Organizasyon 2025",
    description: "Erdek'te özel tekne kiralama, günlük ve haftalık kiralık tekne fiyatları ve organizasyon bilgileri.",
    date: "2025-10-01",
    readTime: 5,
    category: "Aktiviteler",
    coverEmoji: "🛥️",
    keywords: ["erdek tekne kiralama", "erdek kiralık tekne", "erdek özel tekne", "kapıdağ tekne turu", "erdek yat kiralama"],
    content: "<p>Erdek'te kendi özel teknenizle Kapıdağ koylarını keşfetmek tatili bambaşka bir boyuta taşır.</p><h2>Tekne Tipleri ve Fiyatlar</h2><ul><li><strong>Günlük tur teknesi (grup):</strong> Kişi başı 300-500 TL</li><li><strong>Özel sürat teknesi:</strong> Günlük 1500-3000 TL</li><li><strong>Yelkenli kiralama:</strong> Günlük 2000-4000 TL</li></ul><h2>Organizasyon</h2><p>Erdek iskelesi çevresindeki acenteler tekne organizasyonu yapmaktadır. Yaz sezonunda önceden rezervasyon önerilir.</p><h2>Ne Görürsünüz?</h2><p>Kapıdağ koyları, Narlı Gölü girişi, Domurcalı ve Baldım'ın gizli koyları tekne turunun şaheser durakları.</p>",
  },
  {
    slug: "erdek-saglik-eczane-hastane",
    title: "Erdek'te Sağlık Hizmetleri — Hastane, Eczane ve Acil 2025",
    description: "Erdek'te hastane, sağlık ocağı, eczane yerleri ve tatilde acil durumda ne yapılır?",
    date: "2025-10-05",
    readTime: 4,
    category: "Pratik Bilgiler",
    coverEmoji: "🏥",
    keywords: ["erdek hastane", "erdek eczane", "erdek sağlık", "erdek acil servis", "tatilde sağlık"],
    content: "<p>Tatilde sağlık sorunlarına karşı hazırlıklı olmak önemlidir.</p><h2>Sağlık Ocağı</h2><p>Erdek merkezde Aile Sağlığı Merkezi ve devlet hastanesi mevcuttur. Hafif rahatsızlıklar için yeterlidir.</p><h2>Eczaneler</h2><p>Erdek merkezde birden fazla eczane bulunmaktadır. Nöbetçi eczane için 182'yi arayabilirsiniz.</p><h2>Acil Durumda</h2><p>Ciddi aciller için en yakın tam donanımlı hastane Bandırma'dadır (yaklaşık 45 km). Acil: 112.</p><h2>Önlem Önerileri</h2><ul><li>Güneş yanığı kremi mutlaka alın</li><li>Denizanası sokmalarına karşı antihistaminik bulundurun</li></ul>",
  },
  {
    slug: "erdek-sahil-promenad-yuruyus",
    title: "Erdek Sahil Promenadı — Yürüyüş Güzergahı ve Manzara Noktaları",
    description: "Erdek sahil yürüyüş güzergahı, promenad boyunca kafeler, manzara noktaları ve pratik bilgiler.",
    date: "2025-10-08",
    readTime: 4,
    category: "Aktiviteler",
    coverEmoji: "🌊",
    keywords: ["erdek sahil yürüyüşü", "erdek promenad", "erdek sahil şeridi", "erdek yürüyüş güzergahı"],
    content: "<p>Erdek sahil promenadı, tatilcilerin en çok vakit geçirdiği alandır. Deniz kenarında uzanan bu yürüyüş yolu hem sabah hem akşam farklı güzellikler sunar.</p><h2>Promenad Boyunca</h2><ul><li>Çay bahçeleri ve sahil kafeleri</li><li>Dondurma ve gözleme tezgahları</li><li>Balıkçı tekneleri manzarası</li><li>Çocuklar için oyun alanları</li></ul><h2>En İyi Zaman</h2><p>Sabah 07:00-09:00 arası serin ve sakin. Akşam 18:00-21:00 arası ise en hareketli ve manzaralı dönem.</p>",
  },
  {
    slug: "erdek-hamzakoy-rehberi",
    title: "Hamzaköy Erdek — Sakin Bir Koy ve Balıkçı Koyu Rehberi",
    description: "Hamzaköy'e ulaşım, plaj, marina, restoranlar ve Kapıdağ'ın bu sakin köşesi hakkında her şey.",
    date: "2025-10-10",
    readTime: 5,
    category: "Plajlar",
    coverEmoji: "⚓",
    keywords: ["hamzaköy erdek", "hamzaköy koyu", "kapıdağ hamzaköy", "erdek marina", "hamzaköy balıkçı"],
    content: "<p><strong>Hamzaköy</strong>, Kapıdağ Yarımadası'nda küçük bir marinası ve otantik balıkçı atmosferiyle kalabalıktan uzak tatil arayanların sığınağıdır.</p><h2>Ulaşım</h2><p>Erdek'ten Hamzaköy'e dolmuş seferleri mevcuttur. Araçla yaklaşık 25 dakika sürer.</p><h2>Marina ve Tekne</h2><p>Hamzaköy'deki küçük marina tekne yatırmak ve yakıt almak için elverişlidir. Yatçılar arasında popüler bir molalama noktasıdır.</p><h2>Yeme-İçme</h2><p>Marinanın yanındaki küçük balıkçı restoranları günlük taze balık servis eder. Turistik kalabalıktan uzak, yerel atmosfer sunarlar.</p>",
  },
  {
    slug: "erdek-bandirma-ulasim",
    title: "Bandırma'dan Erdek'e Nasıl Gidilir? — Ulaşım ve Güzergah 2025",
    description: "Bandırma'dan Erdek'e otobüs, minibüs ve araçla ulaşım. Mesafe, süre ve güzergah bilgileri.",
    date: "2025-10-12",
    readTime: 4,
    category: "Pratik Bilgiler",
    coverEmoji: "🚐",
    keywords: ["bandırma erdek", "bandırma erdek otobüs", "bandırma erdek mesafe", "bandırma erdek minibüs"],
    content: "<p>Bandırma, İstanbul'dan feribotla gelindiğinde Erdek yolculuğunun aktarma noktasıdır.</p><h2>Mesafe ve Süre</h2><p>Bandırma-Erdek mesafesi yaklaşık <strong>45 km</strong>dir. Araçla 35-40 dakika, minibüsle 50-60 dakika sürer.</p><h2>Minibüs ve Otobüs</h2><p>Bandırma otogarından Erdek'e düzenli minibüs seferleri işlemektedir. Yaz sezonunda sıklık artar.</p><h2>Araçla Güzergah</h2><p>Bandırma'dan çıkış yaparak Erdek istikametini takip edin. Yol boyu Marmara manzarası eşlik eder.</p>",
  },
  {
    slug: "erdek-tarihi-ve-kulturu",
    title: "Erdek'in Tarihi — Antik Artake'den Günümüze",
    description: "Erdek'in antik çağlardan Osmanlı ve Cumhuriyet dönemine uzanan zengin tarihsel geçmişi.",
    date: "2025-10-15",
    readTime: 8,
    category: "Erdek Rehberi",
    coverEmoji: "🏛️",
    keywords: ["erdek tarihi", "erdek antik", "artake erdek", "erdek bizans", "erdek osmanlı tarihi"],
    content: "<p>Erdek'in bulunduğu topraklar, binlerce yıllık bir tarihe ev sahipliği yapmaktadır. Antik çağda bu bölgede <strong>Artake</strong> adlı bir yerleşim yeri mevcuttu.</p><h2>Antik Dönem</h2><p>Artake, Propontis (Marmara Denizi) kıyısında konumlanan ticaret açısından önemli bir antik kentti. Myzialılar, Persler ve Makedonyalılar bu topraklara hâkim oldu.</p><h2>Bizans Dönemi</h2><p>Bizans döneminde bölge stratejik önemini korudu. Kapıdağ Yarımadası'ndaki manastır kalıntıları bu dönemin izlerini taşımaktadır.</p><h2>Osmanlı ve Cumhuriyet</h2><p>1923 Nüfus Mübadelesi sonrası Erdek, Selanik'ten gelen Türk mübadillerin yurdu oldu. Bu kültürel harman bugün hâlâ hissedilmektedir.</p>",
  },
  {
    slug: "erdek-pasalimani-adasi",
    title: "Paşalimanı Adası — Erdek'ten Günübirlik Gezi Rehberi",
    description: "Paşalimanı Adası'na Erdek'ten nasıl gidilir, adada gezilecek yerler, plajlar ve konaklama.",
    date: "2025-10-18",
    readTime: 6,
    category: "Günübirlik Geziler",
    coverEmoji: "🌊",
    keywords: ["paşalimanı adası", "erdekten paşalimanı", "paşalimanı feribot", "paşalimanı gezisi", "marmara adaları"],
    content: "<p><strong>Paşalimanı Adası</strong>, Marmara Denizi'ndeki en sakin ve el değmemiş adalardan biridir. Kalabalıktan uzak doğal güzellikleriyle Avşa veya Marmara Adası'na alternatif arayan gezginler için mükemmeldir.</p><h2>Erdek'ten Ulaşım</h2><p>Erdek iskelesinden Paşalimanı'na düzenli feribot seferleri mevcuttur. Yolculuk süresi yaklaşık 1,5-2 saattir.</p><h2>Adada Ne Yapılır?</h2><ul><li>Sakin plajlarda yüzme</li><li>Adayı yürüyerek keşfetme</li><li>Yerel balıkçı ailelerinden taze balık yeme</li><li>Bisikletle ada turu</li></ul><h2>Tavsiye</h2><p>Ada konaklama için sınırlı imkân sunmaktadır; günübirlik ziyaret önerilir.</p>",
  },
  {
    slug: "erdek-bursa-gezi-plani",
    title: "Bursa'dan Erdek'e Gezi — Mesafe, Ulaşım ve Rota 2025",
    description: "Bursa'dan Erdek'e nasıl gidilir, mesafe, güzergah ve Erdek-Bursa kombinasyonu tatil planı.",
    date: "2025-10-20",
    readTime: 5,
    category: "Günübirlik Geziler",
    coverEmoji: "🛣️",
    keywords: ["bursa erdek", "bursa erdek mesafe", "bursa erdek güzergah", "bursa erdek tatil"],
    content: "<p>Bursa'dan Erdek'e ulaşım oldukça kolaydır; iki şehir arasındaki mesafe yaklaşık <strong>130 km</strong>dir.</p><h2>Araçla Güzergah</h2><p>Bursa - Mustafakemalpaşa - Bandırma - Erdek güzergahını izleyin. Yolculuk süresi yaklaşık 2 saattir.</p><h2>Toplu Taşıma</h2><p>Bursa'dan Bandırma'ya otobüs, Bandırma'dan Erdek'e minibüs ile ulaşılabilir.</p><h2>Kombinasyon Tatil</h2><p>Bursa'nın tarihi zenginliklerini keşfedip ardından Erdek'e geçmek mükemmel bir kombinasyon sunar. Uludağ veya İznik'ten sonra Erdek sahili tatilinizi taçlandırır.</p>",
  },
  {
    slug: "erdek-balikesir-gunubirlik",
    title: "Balıkesir'den Erdek'e Günübirlik Gezi Rehberi",
    description: "Balıkesir şehir merkezinden Erdek'e günübirlik gezi planı, ulaşım ve görülecek yerler.",
    date: "2025-10-22",
    readTime: 4,
    category: "Günübirlik Geziler",
    coverEmoji: "🚗",
    keywords: ["balıkesir erdek günübirlik", "balıkesirden erdek", "balıkesir erdek otobüs", "erdek günübirlik"],
    content: "<p>Balıkesir'den Erdek'e günübirlik gezi çok kolaydır; yaklaşık <strong>95 km</strong> ve 1,5 saatlik yolculukla Marmara kıyısındasınız.</p><h2>Ulaşım</h2><p>Balıkesir otogarından Erdek'e düzenli otobüs seferleri mevcuttur. Saat başı veya 2 saatte bir sefer işlemektedir.</p><h2>Günübirlik Plan</h2><ul><li>Sabah 09:00 Balıkesir'den çıkış</li><li>10:30 Erdek'e varış, sahil yürüyüşü</li><li>12:00 Balık restoranında öğle yemeği</li><li>14:00 Plaj veya tekne turu</li><li>17:00 Erdek'ten dönüş</li></ul>",
  },
  {
    slug: "erdek-kusadasi-karsilastirma",
    title: "Erdek mi Kuşadası mı? — Tatil Destinasyonu Karşılaştırması",
    description: "Erdek ve Kuşadası arasında tatil seçimi: fiyat, kalabalık, deniz kalitesi ve aktivite karşılaştırması.",
    date: "2025-10-25",
    readTime: 6,
    category: "Gezi Rehberi",
    coverEmoji: "⚖️",
    keywords: ["erdek kuşadası karşılaştırma", "erdek mi kuşadası mı", "marmara tatil", "ege tatil", "erdek avantajları"],
    content: "<p>Her yaz tatil yerini seçmekte zorlananlar için Erdek ve Kuşadası arasındaki temel farkları karşılaştırdık.</p><h2>Fiyat</h2><p>Erdek, Kuşadası'na kıyasla genellikle <strong>yüzde 30-50 daha uygun</strong> fiyatlı konaklama sunar. Yeme-içme fiyatları da belirgin biçimde daha düşüktür.</p><h2>Kalabalık</h2><p>Kuşadası yaz aylarında çok yoğunlaşırken Erdek daha sakin kalmaktadır. Kalabalıktan kaçmak isteyenler için Erdek ideal seçimdir.</p><h2>Deniz Kalitesi</h2><p>Her iki destinasyon da temiz deniz sunar. Erdek'in Kapıdağ koyları özellikle berrak ve sakindir.</p><h2>Aktiviteler</h2><p>Kuşadası daha fazla gece hayatı ve eğlence sunarken Erdek doğa, tekne ve balıkçılık konusunda öne çıkar.</p>",
  },
  {
    slug: "erdek-feribot-takvimi",
    title: "Erdek Feribot Takvimi — Ada Seferleri ve Saatler 2025",
    description: "Erdek iskelesinden kalkan feribot seferleri, ada takvimi, bilet fiyatları ve rezervasyon bilgileri.",
    date: "2025-10-28",
    readTime: 5,
    category: "Pratik Bilgiler",
    coverEmoji: "⛴️",
    keywords: ["erdek feribot", "erdek feribot takvimi", "erdek ada seferleri", "erdek iskele", "marmara adaları feribot"],
    content: "<p>Erdek iskelesi, Marmara Adaları'na açılan kapıdır. Yaz sezonunda düzenli feribot seferleri ile adalara ulaşmak oldukça kolaydır.</p><h2>Hangi Adalara Sefer Var?</h2><ul><li><strong>Avşa Adası:</strong> Günde 3-5 sefer (yaz), yaklaşık 1s 15dk</li><li><strong>Marmara Adası:</strong> Günde 1-2 sefer, yaklaşık 2 saat</li><li><strong>Paşalimanı:</strong> Günde 1-2 sefer, yaklaşık 1,5-2 saat</li></ul><h2>Bilet Fiyatları (2025)</h2><p>Avşa gidiş-dönüş yaklaşık 280-350 TL, Marmara Adası yaklaşık 350-450 TL (fiyatlar değişkenlik gösterebilir).</p><h2>Rezervasyon</h2><p>Temmuz-Ağustos döneminde feribotlar dolmaktadır; önceden bilet almak önerilir.</p>",
  },
  {
    slug: "erdek-tatil-butce-planlama",
    title: "Erdek Tatili Bütçe Planlaması — Ekonomik Tatil Rehberi 2025",
    description: "Erdek tatili için bütçe planlaması: konaklama, yemek, aktivite ve ulaşım maliyetleri.",
    date: "2025-11-01",
    readTime: 6,
    category: "Pratik Bilgiler",
    coverEmoji: "💰",
    keywords: ["erdek tatil bütçe", "erdek ucuz tatil", "erdek tatil maliyeti", "erdek ekonomik tatil", "erdek tatil fiyatları"],
    content: "<p>Erdek, Türkiye'nin en ekonomik deniz tatil destinasyonlarından biridir. Doğru planlama ile bütçe dostu bir tatil mümkündür.</p><h2>Konaklama</h2><ul><li><strong>Pansiyon:</strong> Gece 500-1000 TL (kahvaltı dahil)</li><li><strong>Apart otel:</strong> Gece 800-1500 TL</li><li><strong>Otel:</strong> Gece 1200-3000 TL</li></ul><h2>Yemek</h2><ul><li>Balık restoranı kişi başı: 250-500 TL</li><li>Pide/kebap restoranı: 150-250 TL</li><li>Market alışverişi ile yapılan öğünler: 50-100 TL</li></ul><h2>Aktiviteler</h2><ul><li>Günlük tekne turu: 300-500 TL kişi başı</li><li>Ada feribotu gidiş-dönüş: 280-450 TL</li></ul><h2>Bütçe Özeti</h2><p>2 kişilik 5 gece Erdek tatili için ortalama <strong>10.000-20.000 TL</strong> bütçe yeterlidir (sezona ve tercihlere göre değişir).</p>",
  },
  {
    slug: "erdek-kusbakisi-harita",
    title: "Erdek Haritası — Semtler, Koylar ve Önemli Noktalar",
    description: "Erdek ve çevresinin haritası: merkez, Kapıdağ koyları, iskele, plajlar ve önemli lokasyonlar.",
    date: "2025-11-05",
    readTime: 4,
    category: "Pratik Bilgiler",
    coverEmoji: "🗺️",
    keywords: ["erdek haritası", "erdek nerede", "kapıdağ harita", "erdek koy haritası", "erdek merkez"],
    content: "<p>Erdek'i planlamadan önce coğrafyasına hâkim olmak tatili çok daha kolay ve verimli kılar.</p><h2>Erdek Merkez</h2><p>Erdek'in kalbi; iskele, sahil promenadı, çarşı ve merkez plaj bu bölgede yer alır.</p><h2>Kapıdağ Yarımadası</h2><p>Erdek'ten kuzeybatıya uzanan yarımada; Ocaklar, Narlı, Baldım, Domurcalı ve Hamzaköy koylarını kapsar. Yaklaşık 50 km uzunluğundadır.</p><h2>İskele</h2><p>Ada feribotları ve günlük tekne turları Erdek iskelesinden kalkar. İskele hem ulaşım merkezi hem de akşam yürüyüşünün güzel noktasıdır.</p><h2>Pratik Bilgi</h2><p>Google Maps'te 'Erdek' aratarak interaktif haritaya ulaşabilir, koyların konumlarını görebilirsiniz.</p>",
  },
  {
    slug: "erdek-evcil-hayvanla-tatil",
    title: "Erdek'te Evcil Hayvanla Tatil — Pet Friendly Rehber 2025",
    description: "Erdek'te evcil hayvanınızla tatil yapabilir misiniz? Pet friendly oteller, plajlar ve pratik bilgiler.",
    date: "2025-11-08",
    readTime: 4,
    category: "Pratik Bilgiler",
    coverEmoji: "🐕",
    keywords: ["erdek evcil hayvan tatil", "erdek pet friendly", "erdek köpekle tatil", "erdek hayvanlı otel"],
    content: "<p>Evcil hayvanınızla tatil yapmak istiyorsanız Erdek bazı avantajlar sunmaktadır.</p><h2>Pet Friendly Otel ve Pansiyonlar</h2><p>Erdek'te evcil hayvan kabul eden konaklama seçenekleri mevcuttur. Rezervasyon öncesinde mutlaka sormak gerekir; politikalar değişkenlik gösterir.</p><h2>Plaj</h2><p>Yaz sezonunda bazı plajlarda evcil hayvan girişi kısıtlanabilir. Sabah erken ve akşam geç saatler daha serbesttir.</p><h2>Kapıdağ'da Yürüyüş</h2><p>Evcil hayvanlarla Kapıdağ ormanlık alanlarında yürüyüş yapmak mükemmeldir. Tasma ve su kabı unutmayın.</p>",
  },
  {
    slug: "erdek-balikci-koyleri-otantik",
    title: "Erdek'in Otantik Balıkçı Köyleri — Gizli Kalmış Hazineler",
    description: "Erdek çevresindeki otantik balıkçı köyleri, yerel yaşam ve turistik kalabalıktan uzak alternatifler.",
    date: "2025-11-12",
    readTime: 6,
    category: "Erdek Rehberi",
    coverEmoji: "🏡",
    keywords: ["erdek balıkçı köyleri", "kapıdağ köyleri", "erdek otantik", "erdek gizli yerler", "kapıdağ yerel yaşam"],
    content: "<p>Erdek merkezi ve popüler koyların ötesinde, Kapıdağ Yarımadası'nın derin koylarında zamanın durduğu balıkçı köyleri saklanmaktadır.</p><h2>Domurcalı</h2><p>Ulaşımı biraz zorlu ama bu yüzden hâlâ bozulmamış. Küçük balıkçı barınağı ve çevresindeki kamp alanları doğa tutkunları içindir.</p><h2>Yeniköy</h2><p>Kapıdağ'ın küçük ve sakin köylerinden biri. Turizmin henüz tam anlamıyla uğramadığı otantik bir atmosfer sunar.</p><h2>Baldım</h2><p>Aile pansiyonları ve sakin koyu ile aileler için idealdir. Yazın bile Ocaklar kadar kalabalık olmaz.</p><h2>Neden Gitmelisiniz?</h2><p>Bu köylerde yerel halkın günlük yaşamını gözlemlemek, taze balık almak ve gerçek Marmara kültürünü yaşamak mümkündür.</p>",
  },
  {
    slug: "erdek-marmara-tatil-onerileri",
    title: "Marmara'da Tatil Planlaması — Erdek Dahil En İyi Rotalar 2025",
    description: "Marmara Bölgesi'nde tatil planlaması: Erdek, Bandırma, Bursa ve adaları kapsayan kapsamlı rota rehberi.",
    date: "2025-11-15",
    readTime: 7,
    category: "Gezi Rehberi",
    coverEmoji: "🌍",
    keywords: ["marmara tatil", "marmara tatil rotası", "erdek marmara", "marmara denizi tatil", "balıkesir tatil"],
    content: "<p>Marmara Bölgesi, Erdek başta olmak üzere zengin tatil destinasyonlarıyla dolup taşmaktadır. Kapsamlı bir Marmara tatili planlamak isteyenler için önerilen rotalar:</p><h2>Rota 1: Klasik Marmara (5 Gece)</h2><ul><li><strong>1-2. gece:</strong> Bursa — tarihi çarşı, Uludağ, İznik</li><li><strong>3-5. gece:</strong> Erdek — tekne turu, koylar, balık</li></ul><h2>Rota 2: Ada ve Koy (7 Gece)</h2><ul><li><strong>1-2. gece:</strong> Erdek merkez</li><li><strong>3. gün:</strong> Avşa Adası günübirlik</li><li><strong>4. gün:</strong> Marmara Adası günübirlik</li><li><strong>5-7. gece:</strong> Kapıdağ koylarında kamp veya pansiyon</li></ul><h2>Rota 3: Hafta Sonu Kaçaması (2 Gece)</h2><p>İstanbul'dan feribot ile Bandırma, ardından Erdek. Tekne turu ve plaj. Pazar akşamı dönüş.</p>",
  },
];

export function getBlogPost(slug: string): BlogPost | undefined {
  return blogPosts.find((p) => p.slug === slug);
}

export function getAllSlugs(): string[] {
  return blogPosts.map((p) => p.slug);
}