import os
base = r"c:/Users/agity/Desktop/erdekonline/src/app"
lines = []
lines += [
'"use client";',
'',
'import { useState, useEffect } from "react";',
'import Link from "next/link";',
'import { ArrowLeft, Clock, Star, Heart } from "lucide-react";',
'import Navbar from "@/components/Navbar";',
'import Footer from "@/components/Footer";',
'import WhatsAppButton from "@/components/WhatsAppButton";',
'import { useToast } from "@/components/Toast";',
'',
'const isletmeler = [',
'  { id: 1, isim: "Kalamar Balik Restaurant", kat: "Balik", puan: 4.9, sure: "25-40 dk", emoji: "\U0001f41f", renk: "bg-blue-100", minSiparis: "150\u20ba" },',
'  { id: 2, isim: "Erdek Pide ve Lahmacun", kat: "Pide", puan: 4.7, sure: "20-35 dk", emoji: "\U0001f355", renk: "bg-orange-100", minSiparis: "80\u20ba" },',
'  { id: 4, isim: "Erdek Burger ve Doner", kat: "Fast Food", puan: 4.5, sure: "20-30 dk", emoji: "\U0001f354", renk: "bg-yellow-100", minSiparis: "100\u20ba" },',
'  { id: 5, isim: "Tatli Dukkani Erdek", kat: "Tatli", puan: 4.8, sure: "30-45 dk", emoji: "\U0001f370", renk: "bg-pink-100", minSiparis: "120\u20ba" },',
'];',
'const filtreler = ["Tumu", "Balik", "Pide", "Fast Food", "Tatli"];',
'',
'export default function YemekPage() {',
'  const [aktif, setAktif] = useState("Tumu");',
'  const [siralama, setSiralama] = useState<"puan" | "sure">("puan");',
'  const [favoriler, setFavoriler] = useState<string[]>([]);',
'  const { goster, ToastContainer } = useToast();',
'',
'  useEffect(() => {',
'    try { const raw = localStorage.getItem("eo_favoriler"); setFavoriler(raw ? JSON.parse(raw) : []); }',
'    catch { setFavoriler([]); }',
'  }, []);',
'',
'  function favoriToggle(e: React.MouseEvent, id: number) {',
'    e.preventDefault(); e.stopPropagation();',
'    const sid = String(id);',
'    const eklendi = !favoriler.includes(sid);',
'    const yeni = eklendi ? [...favoriler, sid] : favoriler.filter(f => f !== sid);',
'    setFavoriler(yeni);',
'    localStorage.setItem("eo_favoriler", JSON.stringify(yeni));',
'    goster(eklendi ? "Favorilere eklendi!" : "Favorilerden kaldirildi", eklendi ? "success" : "info");',
'  }',
'',
'  const liste = isletmeler',
'    .filter(b => aktif === "Tumu" || b.kat === aktif)',
'    .sort((a, b) => siralama === "puan" ? b.puan - a.puan : a.sure.localeCompare(b.sure));',
]